// <auto-generated />
using System;
using Dcms.Shared.Data.Audit;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dcms.Shared.Data.Migrations.Audit
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260820172243_InitialAudit")]
    partial class InitialAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dcms.Shared.Data.Audit.AuditChainAnchor", b =>
                {
                    b.Property<Guid>("ChainKey")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date");

                    b.Property<byte[]>("AnchorHmac")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("FirstHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("FirstSeq")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("LastHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("LastSeq")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("PartitionDroppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RowCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SealedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChainKey", "Period");

                    b.ToTable("chain_anchors", "audit");
                });

            modelBuilder.Entity("Dcms.Shared.Data.Audit.AuditChainHead", b =>
                {
                    b.Property<Guid>("ChainKey")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date");

                    b.Property<byte[]>("LastHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChainKey", "Period");

                    b.ToTable("chain_heads", "audit");
                });

            modelBuilder.Entity("Dcms.Shared.Data.Audit.AuditEventRow", b =>
                {
                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("ActorAttribution")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ActorDisplay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ActorRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChainKey")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<short>("HashVersion")
                        .HasColumnType("smallint");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IpTrusted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSandbox")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date");

                    b.Property<byte[]>("PrevHash")
                        .HasColumnType("bytea");

                    b.Property<long>("ProducerSeq")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("RedactionVersion")
                        .HasColumnType("smallint");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResourceLabel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RoutePattern")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<short>("SchemaVersion")
                        .HasColumnType("smallint");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceInstance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint");

                    b.Property<string>("SpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubjectUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("OccurredAt", "Id");

                    b.ToTable("audit_events", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Dcms.Shared.Data.Audit.AuditOutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_audit_outbox_pending")
                        .HasFilter("\"AppliedAt\" IS NULL");

                    b.ToTable("audit_outbox", "audit");
                });
#pragma warning restore 612, 618
        }
    }
}
