using System.Text;
using System.Text.Json;
using Dcms.Shared.Data.Cms;

namespace Dcms.AdminApi.ApiClientGen;

/// <summary>The DCMS-owned files of a Mode B site, as one set.</summary>
/// <param name="Fingerprint">A hash of every file but the manifest — changes exactly when a file does.</param>
public sealed record GeneratedFiles(IReadOnlyDictionary<string, string> Files, string Fingerprint);

/// <summary>
/// The part of a Mode B site DCMS writes and keeps current: the typed client under
/// <c>src/api/</c>, the analytics + consent runtime under <c>src/dcms/</c>, and <c>openapi.json</c>.
///
/// <para><b>One definition.</b> Starter templates, Refresh API and automatic regeneration all
/// write exactly this set, so a site started today and a site refreshed today hold the same files.
/// Before, the starter wrote the whole starter zip and Refresh API re-derived "the generated part"
/// by filtering that zip by path prefix, which kept the two in step only for as long as nobody
/// added a file.</para>
///
/// <para><b>The fingerprint hashes output, not input.</b> Hashing inputs (plugins, domains) would
/// miss the generator itself improving; hashing the build would change on every deploy and rewrite
/// every site's manifest for nothing. Hashing what is written changes precisely when there is
/// something new to write, so the IDE can compare it with the site's manifest and refresh only
/// then.</para>
///
/// <para><c>src/api/manifest.json</c> records the fingerprint and the file list. The list is what
/// makes a later refresh able to delete a file the generator stopped emitting without touching a
/// file the author added beside it.</para>
/// </summary>
public static class GeneratedLayer
{
    public const string ManifestPath = "src/api/manifest.json";
    public const string OpenApiPath = "openapi.json";

    private static readonly string[] OwnedPrefixes = ["src/api/", "src/dcms/"];

    /// <summary>Whether a path is DCMS's to overwrite. Everything else in a site is the author's.</summary>
    public static bool Owns(string path) =>
        path == OpenApiPath || OwnedPrefixes.Any(p => path.StartsWith(p, StringComparison.Ordinal));

    public static GeneratedFiles Build(TenantApiSnapshot api)
    {
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);

        foreach (var (path, content) in TypeScriptClientEmitter.Emit(api.Document, api.Instances, "./runtime"))
        {
            files["src/api/" + path["src/".Length..]] = content; // src/index.ts -> src/api/index.ts
        }
        files["src/api/runtime/index.ts"] = ClientPackageBuilder.RuntimeIndex;
        files["src/api/runtime/types.ts"] = ClientPackageBuilder.RuntimeTypes;
        foreach (var (path, content) in SiteTemplates.DcmsRuntime())
        {
            files[path] = content;
        }
        files[OpenApiPath] = api.Json;

        var digest = new StringBuilder();
        foreach (var (path, content) in files)
        {
            digest.Append(path).Append('\0').Append(content).Append('\0');
        }
        var fingerprint = PluginInstanceFingerprint.Hash(digest.ToString());

        var manifest = new
        {
            comment = "Generated by DCMS. Lists the files it owns in this site; do not edit.",
            fingerprint,
            files = files.Keys.Append(ManifestPath).Order(StringComparer.Ordinal).ToArray(),
        };
        files[ManifestPath] = JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true }) + "\n";

        return new GeneratedFiles(files, fingerprint);
    }
}
