using System.Text;
using System.Text.Json;
using Dcms.Shared.Data.Cms;

namespace Dcms.AdminApi.ApiClientGen;

/// <summary>
/// The Mode D component runtime as a Mode D site carries it: <c>@dcms/site-runtime</c>'s source,
/// embedded from <c>packages/site-runtime/src</c>, under <c>src/dcms/runtime/</c> (ADR 0020).
///
/// <para><b>Separate from <see cref="GeneratedLayer"/></b>, on purpose. That layer is every Mode B
/// site's, and its fingerprint is tenant-wide; folding the runtime into it would push these files
/// into every Mode B repository and give two kinds of site one fingerprint that only one of them
/// matches. This layer has its own manifest, so the builder refreshes it on its own terms.</para>
///
/// <para>It depends on nothing but the deployed build — no tenant input — so it is computed once
/// per process. The fingerprint changes exactly when a deploy changes the runtime, which is when a
/// site opened in the builder picks the new one up; a site nobody opens keeps building against the
/// runtime it last received.</para>
/// </summary>
public static class SiteRuntimeLayer
{
    public const string Root = "src/dcms/runtime/";
    public const string ManifestPath = Root + "manifest.json";
    private const string Prefix = "Dcms.AdminApi.SiteRuntime/";

    private static readonly Lazy<GeneratedFiles> Layer = new(Build);

    public static GeneratedFiles Files => Layer.Value;

    private static GeneratedFiles Build()
    {
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);
        foreach (var name in PackageIo.EmbeddedNames(Prefix))
        {
            files[Root + name[Prefix.Length..]] = PackageIo.ReadEmbedded(name);
        }

        var digest = new StringBuilder();
        foreach (var (path, content) in files)
        {
            digest.Append(path).Append('\0').Append(content).Append('\0');
        }
        var fingerprint = PluginInstanceFingerprint.Hash(digest.ToString());
        var manifest = new
        {
            comment = "Generated by DCMS. The Mode D component runtime; do not edit.",
            fingerprint,
            files = files.Keys.Append(ManifestPath).Order(StringComparer.Ordinal).ToArray(),
        };
        files[ManifestPath] = JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true }) + "\n";
        return new GeneratedFiles(files, fingerprint);
    }
}
