using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Dcms.AdminApi.ApiClientGen;

/// <summary>A tenant plugin instance the generated client should resolve.</summary>
public sealed record GeneratedInstance(string Slug, string PluginId, string Name);

/// <summary>
/// Emits the per-tenant TypeScript layer (<c>types.ts</c> + <c>index.ts</c>) of the
/// downloadable client from the tenant's assembled OpenAPI document plus its enabled
/// plugin instances. The generated code layers a typed resolver tree
/// (<c>api.blog.post.list()</c>) on top of the hand-written <c>@dcms/api-client</c>
/// runtime, which is imported from <paramref name="runtimeModule"/>.
///
/// Content endpoints are derived from the spec (typed from the item schemas); the
/// fixed platform capabilities (search / visitor-auth / chat / analytics) are keyed off
/// the instance's plugin id, since not all of them appear in the OpenAPI paths.
/// </summary>
public static class TypeScriptClientEmitter
{
    public const string DefaultRuntimeModule = "@dcms/api-client";

    public static IReadOnlyDictionary<string, string> Emit(
        JsonObject openApi,
        IReadOnlyList<GeneratedInstance> instances,
        string runtimeModule = DefaultRuntimeModule)
    {
        var schemas = openApi["components"]?["schemas"]?.AsObject() ?? new JsonObject();
        var paths = openApi["paths"]?.AsObject() ?? new JsonObject();

        return new Dictionary<string, string>
        {
            ["src/types.ts"] = EmitTypes(schemas, runtimeModule),
            ["src/index.ts"] = EmitIndex(paths, instances, runtimeModule),
        };
    }

    private static string EmitTypes(JsonObject schemas, string runtimeModule)
    {
        var interfaces = new List<(string Name, string Body)>();
        var usesMedia = false;
        var usesContentRef = false;

        foreach (var (key, node) in schemas.OrderBy(kv => kv.Key, StringComparer.Ordinal))
        {
            if (key.EndsWith("_list", StringComparison.Ordinal))
            {
                continue; // the paged envelope is provided by the runtime's PagedResult<T>
            }
            // Only content items carry a typed `data` payload; skip request-body schemas
            // (e.g. the analytics event), which the runtime already types.
            if (node?["properties"]?["data"] is not JsonObject data)
            {
                continue;
            }

            interfaces.Add((Pascal(key), BuildInterfaceBody(data, ref usesMedia, ref usesContentRef)));
        }

        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by DCMS. Do not edit — re-download to regenerate.");

        var brandImports = new List<string>();
        if (usesMedia) brandImports.Add("MediaRef");
        if (usesContentRef) brandImports.Add("ContentRef");
        if (brandImports.Count > 0)
        {
            sb.AppendLine($"import type {{ {string.Join(", ", brandImports)} }} from '{runtimeModule}';");
        }
        sb.AppendLine();

        if (interfaces.Count == 0)
        {
            // Keep the module valid even when the tenant has no content instances yet.
            sb.AppendLine("export {};");
            return sb.ToString();
        }

        foreach (var (name, body) in interfaces)
        {
            sb.AppendLine($"export interface {name} {{");
            sb.Append(body);
            sb.AppendLine("}");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    private static string BuildInterfaceBody(JsonObject data, ref bool usesMedia, ref bool usesContentRef)
    {
        var properties = data["properties"] as JsonObject ?? [];
        var required = (data["required"] as JsonArray)?
            .Select(n => n!.GetValue<string>())
            .ToHashSet(StringComparer.Ordinal) ?? [];

        var sb = new StringBuilder();
        foreach (var (fieldName, fieldNode) in properties)
        {
            var fieldSchema = fieldNode as JsonObject ?? [];
            var tsType = TsType(fieldSchema, ref usesMedia, ref usesContentRef);
            var optional = required.Contains(fieldName) ? string.Empty : "?";
            sb.AppendLine($"  {FieldKey(fieldName)}{optional}: {tsType};");
        }
        return sb.ToString();
    }

    private static string TsType(JsonObject schema, ref bool usesMedia, ref bool usesContentRef)
    {
        if (schema["$ref"] is JsonValue refValue)
        {
            return Pascal(refValue.GetValue<string>().Split('/')[^1]);
        }

        switch ((schema["type"] as JsonValue)?.GetValue<string>())
        {
            case "string":
                if (schema.ContainsKey("x-dcms-media-category"))
                {
                    usesMedia = true;
                    return "MediaRef";
                }
                if (schema.ContainsKey("x-dcms-content-ref"))
                {
                    usesContentRef = true;
                    return "ContentRef";
                }
                return "string";
            case "integer":
            case "number":
                return "number";
            case "boolean":
                return "boolean";
            case "array":
                var items = schema["items"] as JsonObject ?? [];
                return TsType(items, ref usesMedia, ref usesContentRef) + "[]";
            case "object":
                return "Record<string, unknown>";
            default:
                return "unknown";
        }
    }

    private static string EmitIndex(JsonObject paths, IReadOnlyList<GeneratedInstance> instances, string runtimeModule)
    {
        var typeImports = new SortedSet<string>(StringComparer.Ordinal);
        var runtimeTypeImports = new SortedSet<string>(StringComparer.Ordinal) { "TenantClientOptions" };

        var body = new StringBuilder();
        body.AppendLine("  const http = createHttpCore(options);");
        body.AppendLine("  return {");
        body.AppendLine("    media: {");
        body.AppendLine("      url: (assetId: string, variant?: string) => http.mediaUrl(assetId, variant),");
        body.AppendLine("    },");
        // Generic list/get accessor for any instance — lets untyped/example code work
        // uniformly alongside the typed per-instance tree below.
        body.AppendLine("    content: http.content,");

        foreach (var instance in instances.OrderBy(i => i.Slug, StringComparer.Ordinal))
        {
            var slug = Lit(instance.Slug);
            switch (instance.PluginId)
            {
                case "search":
                    runtimeTypeImports.Add("SearchParams");
                    runtimeTypeImports.Add("SearchResult");
                    body.AppendLine($"    {slug}: {{");
                    body.AppendLine($"      search: (params: SearchParams): Promise<SearchResult> => http.search({slug}, params),");
                    body.AppendLine("    },");
                    break;

                case "visitor-auth":
                    body.AppendLine($"    {slug}: {{");
                    body.AppendLine($"      auth: http.visitorAuth({slug}),");
                    body.AppendLine("    },");
                    break;

                case "live-chat":
                    runtimeTypeImports.Add("ChatMessage");
                    body.AppendLine($"    {slug}: {{");
                    body.AppendLine("      chat: {");
                    body.AppendLine($"        history: (conversationId: string): Promise<ChatMessage[]> => http.chatHistory({slug}, conversationId),");
                    body.AppendLine("      },");
                    body.AppendLine("    },");
                    break;

                case "analytics":
                    runtimeTypeImports.Add("AnalyticsEvent");
                    body.AppendLine($"    {slug}: {{");
                    body.AppendLine($"      collect: (event: AnalyticsEvent): Promise<void> => http.collect(event, {slug}),");
                    body.AppendLine("    },");
                    break;

                default:
                    var contentTypes = ContentTypes(paths, instance.Slug);
                    if (contentTypes.Count == 0)
                    {
                        break;
                    }
                    runtimeTypeImports.Add("ListParams");
                    runtimeTypeImports.Add("PagedResult");
                    runtimeTypeImports.Add("ContentItem");
                    body.AppendLine($"    {slug}: {{");
                    foreach (var contentType in contentTypes)
                    {
                        var ct = Lit(contentType);
                        var typeName = Pascal($"{instance.Slug}_{contentType}");
                        typeImports.Add(typeName);
                        body.AppendLine($"      {ct}: {{");
                        body.AppendLine($"        list: (params?: ListParams): Promise<PagedResult<{typeName}>> => http.listContent<{typeName}>({slug}, {ct}, params),");
                        body.AppendLine($"        get: (slug: string): Promise<ContentItem<{typeName}>> => http.getContent<{typeName}>({slug}, {ct}, slug),");
                        body.AppendLine("      },");
                    }
                    body.AppendLine("    },");
                    break;
            }
        }
        body.AppendLine("  };");

        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by DCMS. Do not edit — re-download to regenerate.");
        sb.AppendLine("import {");
        sb.AppendLine("  createHttpCore,");
        foreach (var type in runtimeTypeImports)
        {
            sb.AppendLine($"  type {type},");
        }
        sb.AppendLine($"}} from '{runtimeModule}';");
        if (typeImports.Count > 0)
        {
            sb.AppendLine($"import type {{ {string.Join(", ", typeImports)} }} from './types';");
        }
        sb.AppendLine();
        sb.AppendLine("export function createTenantClient(options: TenantClientOptions = {}) {");
        sb.Append(body);
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("export type TenantClient = ReturnType<typeof createTenantClient>;");
        // Re-export the shared runtime types and the generated content types so this
        // module is the single import surface (e.g. `import type { ContentItem } from './api'`).
        sb.AppendLine("export type * from './runtime';");
        sb.AppendLine("export type * from './types';");
        return sb.ToString();
    }

    // Content types for an instance = the bare list paths /api/{slug}/{contentType}
    // (a GET with no further path segment or parameter).
    private static IReadOnlyList<string> ContentTypes(JsonObject paths, string slug)
    {
        var prefix = $"/api/{slug}/";
        var result = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var (key, node) in paths)
        {
            if (!key.StartsWith(prefix, StringComparison.Ordinal))
            {
                continue;
            }
            var rest = key[prefix.Length..];
            if (rest.Contains('/') || rest.Contains('{'))
            {
                continue;
            }
            if ((node as JsonObject)?["get"] is null)
            {
                continue;
            }
            result.Add(rest);
        }
        return result.ToList();
    }

    private static string Lit(string value) => JsonSerializer.Serialize(value);

    private static string FieldKey(string name) => IsSafeIdentifier(name) ? name : JsonSerializer.Serialize(name);

    private static string Pascal(string raw)
    {
        var sb = new StringBuilder();
        var upperNext = true;
        foreach (var c in raw)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(upperNext ? char.ToUpperInvariant(c) : c);
                upperNext = false;
            }
            else
            {
                upperNext = true;
            }
        }

        var result = sb.ToString();
        if (result.Length == 0)
        {
            return "Type";
        }
        return char.IsDigit(result[0]) ? "_" + result : result;
    }

    private static bool IsSafeIdentifier(string name)
    {
        if (name.Length == 0 || !(char.IsLetter(name[0]) || name[0] is '_' or '$'))
        {
            return false;
        }
        foreach (var c in name)
        {
            if (!(char.IsLetterOrDigit(c) || c is '_' or '$'))
            {
                return false;
            }
        }
        return true;
    }
}
