import { expect, type Page } from '@playwright/test';
import type { MockApi } from './api';

/** A Mode D site on the mocked server, shared by the builder and agent specs. */

export const SITE = '33333333-3333-3333-3333-333333333333';
export const IDE_FILES = `/api/admin/sites/${SITE}/ide/files`;
export const HOME = 'dcms/pages/home.json';

export const RUNTIME_MANIFEST = JSON.stringify({ fingerprint: 'rt-1', files: ['src/dcms/runtime/index.ts', 'src/dcms/runtime/manifest.json'] });
export const API_MANIFEST = JSON.stringify({ fingerprint: 'fp-1', files: ['src/api/index.ts', 'src/api/manifest.json'] });

/** The server side of a Mode D site: the scaffold, the runtime layer and the API layer. */
export function builderServer(api: MockApi, files: Record<string, string> = {}) {
  api
    .on('GET', '/api/admin/sites/:id', { id: SITE, name: 'Acme', renderMode: 'ReactBuilder', slug: 'acme' })
    .on('GET', '/api/admin/sites/:id/ide', { branch: 'main', baseSha: 'abc1234', version: 1, files, hashes: {} })
    .on('PATCH', '/api/admin/sites/:id/ide/files', { version: 2, hashes: {} })
    .on('GET', '/api/admin/sites/:id/starter-files', {
      fingerprint: 'fp-1',
      files: {
        'package.json': '{ "name": "dcms-site" }',
        'src/main.tsx': '// entry\n',
        'src/api/index.ts': '// AUTO-GENERATED by DCMS fp-1\n',
        'src/api/manifest.json': API_MANIFEST,
        'src/dcms/runtime/index.ts': '// runtime\n',
        'src/dcms/runtime/manifest.json': RUNTIME_MANIFEST,
      },
    })
    .on('GET', '/api/admin/site-runtime', {
      fingerprint: 'rt-1',
      files: { 'src/dcms/runtime/index.ts': '// runtime\n', 'src/dcms/runtime/manifest.json': RUNTIME_MANIFEST },
    })
    .on('GET', '/api/admin/api-fingerprint', { fingerprint: 'fp-1' })
    .on('GET', '/api/admin/sites/:id/git/changes', []);
}

/** The last saved text of any file. */
export function saved(api: MockApi, path: string): string | null {
  const puts = api
    .requestsTo('PATCH', IDE_FILES)
    .map((r) => (r.body as { put?: Record<string, { content?: string } | string> }).put?.[path])
    .filter((v) => v !== undefined);
  const last = puts.at(-1);
  if (last === undefined) return null;
  return typeof last === 'string' ? last : (last.content ?? null);
}

export const doc = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;

export async function open(page: Page, api: MockApi, files: Record<string, string>) {
  // The generated layers' stand-ins, unless the spec brings the real files.
  builderServer(api, {
    'src/api/manifest.json': API_MANIFEST,
    'src/dcms/runtime/index.ts': '// runtime\n',
    'src/dcms/runtime/manifest.json': RUNTIME_MANIFEST,
    ...files,
  });
  await page.setViewportSize({ width: 1600, height: 950 });
  await page.goto(`/sites/${SITE}`);
  const frame = page.frameLocator('iframe.gjs-frame');
  await expect(frame.locator('[data-dcms-type="dcms.heading"]').first()).toBeVisible({ timeout: 30000 });
  return frame;
}

