import {
  BIND_TARGETS,
  EMPTY_ATTR,
  FALLBACK_ATTR,
  FORMAT_ATTR,
  IF_ATTR,
  PREFIX_ATTR,
  REPEAT_ATTR,
  SUFFIX_ATTR,
  TRUNCATE_ATTR,
  UNLESS_ATTR,
  BIND_ATTR,
  BLOCKS_DIR,
  GLOBAL_CSS,
  PAGES_DIR,
  REGIONS_DIR,
  SITE_JSON,
  THEME_CSS,
  type ComponentDefinition,
  type DcmsComponentSpec,
} from '@dcms/gjs-schema';
import { BUILTIN_SPECS } from './specs';

/**
 * `AGENTS.md`: the authoring contract, written into every Mode A site's repo.
 *
 * A site's source is now ordinary HTML and CSS in git, which means anything that
 * can edit files can edit the site — the in-IDE assistant, a checked-out clone,
 * an agent running in CI. What none of them can infer from the files alone is
 * the part that makes the output *work here*: that a `<section>` only becomes an
 * editable Hero if it carries `dcms-hero`, that a colour must come from a theme
 * token or the design kit cannot restyle it, that data-bound content is an inert
 * placeholder rather than markup. Left to guess, a model writes valid HTML that
 * degrades the site into something the builder can no longer edit.
 *
 * So the contract is **generated, not written**: every list below is derived
 * from the same declarations the builder itself uses, and the file is rewritten
 * on every save. It cannot go stale, and it cannot be lost — deleting it just
 * means the next save puts it back. `AGENTS.md` because that is the filename
 * coding agents already look for, so it is picked up without configuration.
 *
 * It is source-only: the assembler does not publish it (see `SourceOnly` in
 * StaticSiteAssembler), so it never appears at a public URL.
 */

export interface GuideContext {
  siteName?: string;
  /** `--dcms-*` custom properties this site's theme defines, by name. */
  themeVariables: readonly string[];
  /** The tenant's own components (`blocks/<name>.json`). */
  components: readonly ComponentDefinition[];
  pages: readonly { path: string; title: string; slug: string }[];
}

/** The heading every generated guide starts with, so a stale copy is obvious. */
export const GUIDE_HEADER = '<!-- Generated by the DCMS builder. Do not edit: it is rewritten on every save. -->';

export function renderAiGuide(ctx: GuideContext): string {
  const sections = [
    GUIDE_HEADER,
    `# Building ${ctx.siteName ? `“${ctx.siteName}”` : 'this site'}`,
    intro(),
    layout(),
    manifestSection(ctx),
    markupRules(),
    themeSection(ctx),
    catalogue(BUILTIN_SPECS),
    placeholderSection(),
    componentSection(ctx),
    checklist(),
  ];
  return `${sections.join('\n\n')}\n`;
}

function intro(): string {
  return [
    'This repository *is* the website. There is no build step and no framework:',
    'the publisher wraps each page body in a document shell, links the stylesheets,',
    'and uploads the result. What you write is what ships.',
    '',
    'The same files are edited visually in the DCMS builder. Markup that follows the',
    'conventions below stays editable there; markup that does not still renders, it',
    'just becomes an opaque block the author can only change in code.',
  ].join('\n');
}

function layout(): string {
  return [
    '## Files',
    '',
    '```',
    `${SITE_JSON}              pages, navigation, regions, layouts, theme, settings`,
    `${PAGES_DIR}/<slug>.html       one page's body markup (no <html>, <head>, <body>)`,
    `${REGIONS_DIR}/<slug>.html     a band shared by every page whose layout names it`,
    `${THEME_CSS}      GENERATED from site.json — never edit`,
    `${GLOBAL_CSS}     rules shared by every page`,
    'styles/pages/<slug>.css  rules for one page only',
    `${BLOCKS_DIR}/<name>.json     a component this tenant built (see below)`,
    '```',
    '',
    'Adding a page means **both**: an entry in `site.json.pages` and a',
    `\`${PAGES_DIR}/<slug>.html\` file whose name matches its \`slug\`. One without the`,
    'other is a page that does not exist or a file that never ships.',
  ].join('\n');
}

function manifestSection(ctx: GuideContext): string {
  const pages = ctx.pages.length
    ? ctx.pages.map((p) => `- \`${p.path}\` → \`${PAGES_DIR}/${p.slug}.html\` — ${p.title}`).join('\n')
    : '_(none yet)_';
  return [
    '## Pages and routes',
    '',
    pages,
    '',
    'A route may end in a `:param` segment — a **detail route**. `/events/:slug` is',
    'one page that answers every address under `/events/`, and the data-bound block',
    'on it shows whichever item the address names. That is how a list links through',
    'to a single item: the list block sets `itemLink` to `/events/{slug}`, and the',
    'detail page at `/events/:slug` renders the item.',
    '',
    'Do not put a detail route in `site.json.nav` — it is not an address.',
  ].join('\n');
}

function markupRules(): string {
  return [
    '## Writing markup',
    '',
    '- A page file is a **body fragment**. No `<html>`, `<head>`, `<body>` or `<script>`.',
    '- Give every element you style a class, and put the rules in a stylesheet.',
    '  Never use a `style=""` attribute: the builder cannot offer inline styles as',
    '  editable properties, and a design kit cannot reach them.',
    '- Use the theme variables for colour, spacing, radius, shadow and type. A',
    '  hard-coded `#1e293b` is a value no design kit can change, which is the one',
    '  thing that makes a site un-restyleable.',
    '- Prefer flow layout — sections, flex, grid. Avoid absolute positioning.',
    '- Images need `alt`. A link opening a new tab needs `rel="noopener"`.',
    '- Write real copy for the subject at hand, never lorem ipsum.',
  ].join('\n');
}

function themeSection(ctx: GuideContext): string {
  if (ctx.themeVariables.length === 0) {
    return [
      '## Theme',
      '',
      'This site defines no theme tokens yet. Pick a design kit in the builder, or',
      `add tokens to \`${SITE_JSON}.theme\` — \`${THEME_CSS}\` is regenerated from it.`,
    ].join('\n');
  }
  return [
    '## Theme variables',
    '',
    `Defined by \`${SITE_JSON}.theme\` and emitted into \`${THEME_CSS}\`. Use these:`,
    '',
    '```css',
    ctx.themeVariables.map((name) => `var(${name})`).join('\n'),
    '```',
  ].join('\n');
}

/** The built-in catalogue, grouped the way the palette groups it. */
function catalogue(specs: readonly DcmsComponentSpec[]): string {
  const groups = new Map<string, DcmsComponentSpec[]>();
  for (const spec of specs) {
    const key = spec.group ?? spec.category ?? 'other';
    const bucket = groups.get(key);
    if (bucket) bucket.push(spec);
    else groups.set(key, [spec]);
  }

  const body = [...groups.entries()].map(([group, list]) => {
    const rows = list
      .map((spec) => {
        const identity = spec.identityClass ? `\`${spec.identityClass}\`` : '—';
        const children = spec.acceptsChildren ? ' · holds children' : '';
        const docs = spec.docs ? ` — ${firstSentence(spec.docs)}` : '';
        return `| ${spec.label} | \`<${spec.tag}>\` | ${identity} |${children ? ' yes' : ' no'} |${docs.replace(/^ — /, ' ')} |`;
      })
      .join('\n');
    return [
      `### ${group}`,
      '',
      '| Block | Tag | Identity class | Children | Notes |',
      '| --- | --- | --- | --- | --- |',
      rows,
    ].join('\n');
  });

  return [
    '## Block catalogue',
    '',
    'A component is recognised by its **identity class**, nothing else: writing',
    '`<section class="dcms-hero">…</section>` produces an editable Hero on the canvas.',
    'Variants are `data-*` attributes on the same element (`data-variant`, `data-align`,',
    '`data-columns`, `data-tone`, `data-size`) — the block stylesheet targets them, so',
    'they change the look without new CSS.',
    '',
    ...body,
  ].join('\n\n');
}

function placeholderSection(): string {
  return [
    '## Content from a plugin (data-bound blocks)',
    '',
    'Content that lives in the CMS is **not** written into the page. Emit an empty',
    'placeholder; the published page fills it in at run time, and the builder canvas',
    'shows the real content while editing.',
    '',
    '```html',
    '<div class="dcms-collection"',
    '     data-dcms-component="Blog.Posts"',
    `     data-dcms-props='{"heading":"Latest","layout":"cards","itemLink":"/blog/{slug}"}'`,
    `     data-dcms-bindings='[{"propPath":"items","instanceSlug":"blog","query":{"contentType":"post","pageSize":6}}]'></div>`,
    '```',
    '',
    '- `instanceSlug` must name a plugin instance this tenant has **enabled**, and',
    '  `contentType` one of its content types. Anything else renders empty.',
    '- Leave the element itself empty. Content you write inside is overwritten.',
    '- `propPath` is `items` for a list, `item` for a detail view (which reads the',
    '  slug from the page URL — see detail routes above).',
    '',
    '### Presentation props',
    '',
    '| Prop | What it does |',
    '| --- | --- |',
    '| `heading`, `subheading` | Shown above the items. |',
    '| `moreLabel`, `moreHref` | A “see all” link beside the heading. |',
    '| `layout` | `cards`, `tiles`, `list`, `compact`, `feature`, `article`, `video`, `audio`, `downloads`. |',
    '| `arrangement`, `columns` | `grid` / `masonry` / `carousel`, and how many across. |',
    '| `cardVariant` | Passed to `.dcms-card[data-variant]`. |',
    '| `excerptLength` | Trim body text to N characters, cut at a word. |',
    '| `itemLink` | Where each item links: `/events/{slug}`, or `/events/` for the same thing. |',
    '| `linkLabel` | Text of the per-item link, in layouts that show one. |',
    '| `emptyText` | Shown when nothing is published. |',
    '| `titleField`, `bodyField`, `imageField`, `metaField`, `tagsField`, `linkField` | Which field fills which slot. `-` means “leave this out”. |',
    '',
    'Field names are guessed from convention when unmapped, which fails as soon as a',
    'tenant names its headline field something other than `title`. Map them.',
    '',
    '### Tags',
    '',
    'Tags cross collections — the same tag can sit on an event, a gallery item and a',
    'post — so they have their own index rather than living inside one plugin:',
    '',
    '- `GET /api/tags` — every tag the site publishes, most used first, each with the',
    '  collections and fields it appears in and a ready-made call for that combination.',
    '- `GET /api/<instance>/<type>?tag=<tag>` — that collection, filtered. Add',
    '  `&tagField=<field>` for a type carrying more than one tag list.',
    '',
    'The endpoint only exists on sites whose content actually uses tags; check the',
    'site’s own `/api/openapi.json` before building a page around it.',
  ].join('\n');
}

function componentSection(ctx: GuideContext): string {
  const own = ctx.components.length
    ? ctx.components
        .map((c) => {
          const kind = c.source
            ? `data-bound (${c.source.instanceSlug}/${c.source.contentType}, ${c.source.mode})`
            : 'snippet';
          return `- \`custom:${c.name}\` — ${c.label} — ${kind}`;
        })
        .join('\n')
    : '_This site has no components of its own yet._';

  return [
    '## Components this tenant built',
    '',
    own,
    '',
    `A component is \`${BLOCKS_DIR}/<name>.json\`: a label, optional props, an optional`,
    'data `source`, and a `template`. The template is **ordinary HTML carrying binding',
    'attributes** — never a string with `{{ }}` holes — which is what lets it be laid',
    'out on the canvas and hand-edited here.',
    '',
    '```html',
    '<article class="dcms-c-event-card">',
    `  <img ${BIND_ATTR}="src:cover" ${IF_ATTR}="cover" />`,
    `  <h3 ${BIND_ATTR}="text:nadpis"></h3>`,
    `  <p ${BIND_ATTR}="text:perex" ${TRUNCATE_ATTR}="140"></p>`,
    `  <a ${BIND_ATTR}="href:#slug" ${PREFIX_ATTR}="/events/">Read more</a>`,
    '</article>',
    '```',
    '',
    '### Attributes',
    '',
    '| Attribute | Meaning |',
    '| --- | --- |',
    `| \`${BIND_ATTR}="<target>:<source>"\` | Fill this element. Target defaults to \`text\`. |`,
    `| \`${REPEAT_ATTR}\` | Repeat once per fetched item. |`,
    `| \`${REPEAT_ATTR}="<source>"\` | Repeat once per entry of that array on the item in scope — nest freely. |`,
    `| \`${IF_ATTR}\` / \`${UNLESS_ATTR}\` | Drop the element when the source is empty / present. |`,
    `| \`${FORMAT_ATTR}\` | \`date\`, \`media\`, or \`raw\` to turn the guesses off. |`,
    `| \`${TRUNCATE_ATTR}\` | Trim to N characters, at a word. |`,
    `| \`${PREFIX_ATTR}\` / \`${SUFFIX_ATTR}\` | Wrapped around the value — how \`/blog/\` + a slug becomes a link. |`,
    `| \`${FALLBACK_ATTR}\` | Used when the source resolves to nothing. |`,
    `| \`${EMPTY_ATTR}\` | Kept only when the list it sits beside is empty. |`,
    '',
    `Bind targets: ${BIND_TARGETS.map((t) => `\`${t}\``).join(', ')}. Values land as text and`,
    'attribute values, never as markup — `html` is the one exception, and is opt-in',
    'precisely for that reason.',
    '',
    '### Sources',
    '',
    '| Prefix | Reads |',
    '| --- | --- |',
    '| _(none)_ | A field of the item. Dotted paths work; a bare name also finds it one level down, which is where a plugin nests its tenant-defined fields. |',
    '| `@name` | A prop of the component, as set in the inspector. |',
    '| `#slug`, `#id` | The item envelope. |',
    '| `#index`, `#number`, `#count` | Position (0-based), position (1-based), list length. |',
    '| `#first`, `#last`, `#even`, `#odd` | Conditions — use with `data-dcms-if` / `data-dcms-unless`. |',
    '| `#parity` | `even` or `odd`. Bind to `class` to stripe a list. |',
    '| `#value` | Inside a repeat over plain values, the value itself. |',
  ].join('\n');
}

function checklist(): string {
  return [
    '## Before you finish',
    '',
    '- [ ] Every new page has both a `site.json` entry and a `pages/<slug>.html` file.',
    '- [ ] Every colour, space, radius and font size is a `var(--dcms-…)`.',
    '- [ ] No `style=""` attributes, no `<script>`, no absolute positioning.',
    '- [ ] Sections that should be editable carry their identity class.',
    '- [ ] Plugin placeholders name an enabled instance and a real content type.',
    '- [ ] Lists that lead somewhere set `itemLink`, and that route exists as a page.',
    '- [ ] Images have `alt`; external links have `rel="noopener"`.',
  ].join('\n');
}

/** Enough of a spec's docs to be useful in a table row. */
function firstSentence(docs: string): string {
  const cut = docs.split(/(?<=\.)\s/)[0] ?? docs;
  return (cut.length > 110 ? `${cut.slice(0, 110)}…` : cut).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
