<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="$(DcmsSrcRoot)PluginSdk\Dcms.PluginSdk.Runtime\Dcms.PluginSdk.Runtime.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.Analytics\Dcms.Plugins.Analytics.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.Articles\Dcms.Plugins.Articles.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.AudioLibrary\Dcms.Plugins.AudioLibrary.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.Blog\Dcms.Plugins.Blog.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.Carousel\Dcms.Plugins.Carousel.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.FileDownloads\Dcms.Plugins.FileDownloads.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.ImageGallery\Dcms.Plugins.ImageGallery.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.LiveChat\Dcms.Plugins.LiveChat.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.Search\Dcms.Plugins.Search.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.VideoGallery\Dcms.Plugins.VideoGallery.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.VideoStreaming\Dcms.Plugins.VideoStreaming.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.VisitorAuth\Dcms.Plugins.VisitorAuth.csproj" />
  </ItemGroup>

</Project>
