#!/usr/bin/env bash
#
# Resolves every service image at a given tag to its immutable digest and writes a compose
# overlay pinning them.
#
# Why digests and not the tag itself:
#
#   * A tag is a moving pointer. Deploying `:abc1234` twice can deploy two different images
#     if anything re-pushed that tag in between; deploying `@sha256:...` cannot.
#   * Rollback becomes exact. The previous deploy's overlay IS the previous release --
#     `scripts/deploy.sh --rollback` re-applies a file, with no dependence on what a tag
#     happens to point at now.
#   * It makes the promotion honest. A release tag redeploys the digests that were already
#     built and tested on master, so production runs the bits dev validated rather than a
#     rebuild of the same source.
#
# Usage:
#   scripts/ci/resolve-digests.sh <registry-image-prefix> <tag> [output-file]
#
#   scripts/ci/resolve-digests.sh registry.example.com/group/project abc1234 images.yml
#
# Requires `docker` with access to the registry (a plain `docker login` is enough).

set -euo pipefail

PREFIX="${1:?usage: resolve-digests.sh <registry-image-prefix> <tag> [output-file]}"
TAG="${2:?usage: resolve-digests.sh <registry-image-prefix> <tag> [output-file]}"
OUT="${3:-docker-compose.images.yml}"

# compose-service -> image name. Several services share an image deliberately:
# the migration jobs run the admin-api and identity images with --migrate-only, so pinning
# them to anything else would migrate with different code than the services run.
#
# site-build-sandbox is here even though compose never starts it: site-builder launches it
# with `docker run` against the shared daemon, so it has to be present on the host. See the
# sandbox step in scripts/deploy.sh.
SERVICES="
identity:identity
identity-migrate:identity
admin-api:admin-api
migrate:admin-api
content-api:content-api
media-worker:media-worker
email-worker:email-worker
site-builder:site-builder
site-build-sandbox:site-build-sandbox
site-host:site-host
ai-gateway:ai-gateway
platform-api:platform-api
edge:edge
admin-spa:admin-spa
platform-spa:platform-spa
log-janitor:log-janitor
"

{
  echo "# Generated by scripts/ci/resolve-digests.sh -- do not edit."
  echo "#"
  echo "# Pins every service to an immutable digest. Deployed as an extra -f overlay and kept"
  echo "# on the target host so --rollback has an exact previous release to return to."
  echo "#"
  echo "# source tag: $TAG"
  echo "# resolved:   $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "services:"
} > "$OUT"

failed=0
for entry in $SERVICES; do
  service="${entry%%:*}"
  image="${entry##*:}"
  ref="$PREFIX/$image:$TAG"

  # --format '{{index .Manifest.Descriptor.digest}}' would need buildx; `docker inspect` after
  # a pull is available everywhere and works with plain docker:cli.
  digest=$(docker buildx imagetools inspect "$ref" --format '{{println .Manifest.Digest}}' 2>/dev/null | head -1 || true)

  if [ -z "$digest" ]; then
    echo "resolve-digests: could not resolve $ref" >&2
    failed=1
    continue
  fi

  echo "  $service:" >> "$OUT"
  echo "    image: $PREFIX/$image@$digest" >> "$OUT"
  echo "  $service -> $image@$digest"
done

if [ "$failed" -ne 0 ]; then
  echo "resolve-digests: one or more images did not resolve; refusing to emit a partial overlay" >&2
  rm -f "$OUT"
  exit 1
fi

echo "resolve-digests: wrote $OUT"
