import { test, expect } from '../fixtures/test';

/**
 * Starting a Mode B site from a template, and keeping its generated API client current.
 *
 * <p>Both write files into the author's site from the server, and both have a failure mode that
 * no unit test sees: a template choice that silently seeds something else, and a refresh that
 * never reaches the draft. So what is asserted here is the draft save — the files that actually
 * leave the browser.</p>
 */

const SITE = '22222222-2222-2222-2222-222222222222';
const IDE_FILES = `/api/admin/sites/${SITE}/ide/files`;

const manifest = (fingerprint: string) =>
  JSON.stringify({ fingerprint, files: ['src/api/index.ts', 'src/api/manifest.json'] });

function site(api: import('../fixtures/api').MockApi, files: Record<string, string>) {
  api
    .on('GET', '/api/admin/sites/:id', { id: SITE, name: 'Acme site', renderMode: 'ReactApp', slug: 'acme-site' })
    .on('GET', '/api/admin/sites/:id/ide', {
      branch: 'main',
      baseSha: 'abc1234',
      version: 1,
      files,
      hashes: Object.fromEntries(Object.keys(files).map((p) => [p, `h-${p}`])),
    })
    .on('GET', '/api/admin/sites/:id/git/changes', [])
    .on('GET', '/api/admin/sites/:id/git/branches', [{ name: 'main', isDefault: true }])
    .on('GET', '/api/admin/sites/:id/git/history', [])
    .on('GET', '/api/admin/sites/:id/builds', [])
    .on('GET', '/api/admin/ai/conversations', [])
    .on('PATCH', '/api/admin/sites/:id/ide/files', { version: 2, hashes: {} });
}

/** Every path any draft save so far has written. */
function savedPaths(api: import('../fixtures/api').MockApi): string[] {
  return api
    .requestsTo('PATCH', IDE_FILES)
    .flatMap((r) => Object.keys((r.body as { put?: Record<string, string> }).put ?? {}));
}

const TEMPLATE_FILES = {
  'AGENTS.md': '# Content site',
  'package.json': '{ "name": "dcms-site" }',
  'index.html': '<div id="root"></div>',
  'src/main.tsx': "import './styles.css';\n",
  'src/App.tsx': 'export function App() { return null; }\n',
  'src/routes.tsx': 'export const router = null;\n',
  'src/api/index.ts': '// AUTO-GENERATED by DCMS fp-1\n',
  'src/api/manifest.json': manifest('fp-1'),
};

test('a new site starts from the template the author picks', async ({ page, api }) => {
  site(api, {});
  api
    .on('GET', '/api/admin/sites/:id/starter-files', ({ query }) =>
      query.get('template') === 'content' ? { fingerprint: 'fp-1', files: TEMPLATE_FILES } : { fingerprint: 'fp-1', files: {} },
    )
    .on('GET', '/api/admin/api-fingerprint', { fingerprint: 'fp-1' });

  await page.setViewportSize({ width: 1600, height: 950 });
  await page.goto(`/sites/${SITE}`);

  const picker = page.getByRole('dialog', { name: /Start your site/i });
  await expect(picker).toBeVisible({ timeout: 25000 });
  // Three real templates, and none of the old choices that produced a site that could not build.
  await expect(picker.getByRole('button', { name: /Content site/ })).toBeVisible();
  await expect(picker.getByRole('button', { name: /Landing page/ })).toBeVisible();
  await expect(picker.getByRole('button', { name: /Blank project/ })).toBeVisible();
  await expect(picker.getByText(/OpenAPI document only/)).toHaveCount(0);

  await picker.getByRole('button', { name: /Content site/ }).click();
  await expect(picker).toBeHidden();

  // The template reached the draft — including the guide the assistant reads and the client.
  await expect.poll(() => savedPaths(api), { timeout: 15000 }).toEqual(
    expect.arrayContaining(['AGENTS.md', 'src/routes.tsx', 'src/api/index.ts']),
  );
  expect(api.requestsTo('GET', `/api/admin/sites/${SITE}/starter-files`)[0].query.get('template')).toBe('content');
});

test('a failed generation says so and lets the author try again, instead of seeding something else', async ({ page, api }) => {
  site(api, {});
  let calls = 0;
  api
    .on('GET', '/api/admin/sites/:id/starter-files', async ({ route }) => {
      calls++;
      if (calls === 1) {
        await route.fulfill({ status: 500, contentType: 'application/json', body: '{"error":"boom"}' });
        return;
      }
      return { fingerprint: 'fp-1', files: TEMPLATE_FILES };
    })
    .on('GET', '/api/admin/api-fingerprint', { fingerprint: 'fp-1' });

  await page.setViewportSize({ width: 1600, height: 950 });
  await page.goto(`/sites/${SITE}`);

  const picker = page.getByRole('dialog', { name: /Start your site/i });
  await picker.getByRole('button', { name: /Landing page/ }).click({ timeout: 25000 });

  await expect(picker.getByRole('alert')).toContainText(/could not be generated/i);
  // Nothing was seeded behind the author's back.
  expect(savedPaths(api)).toEqual([]);

  await picker.getByRole('button', { name: /Content site/ }).click();
  await expect(picker).toBeHidden();
  await expect.poll(() => savedPaths(api), { timeout: 15000 }).toContain('AGENTS.md');
});

test('when the tenant’s plugins have changed, the site’s API client is refreshed on open', async ({ page, api }) => {
  site(api, {
    'src/App.tsx': 'export function App() { return null; }\n',
    'src/lib/api.ts': "export const api = 'the author wrote this';\n",
    'src/api/index.ts': '// AUTO-GENERATED by DCMS fp-1\n',
    'src/api/manifest.json': manifest('fp-1'),
  });
  api
    .on('GET', '/api/admin/api-fingerprint', { fingerprint: 'fp-2' })
    .on('GET', '/api/admin/sites/:id/generated-files', {
      fingerprint: 'fp-2',
      files: {
        'src/api/index.ts': '// AUTO-GENERATED by DCMS fp-2\n',
        'src/api/manifest.json': manifest('fp-2'),
        // A server bug must still not be able to overwrite the author's code.
        'src/lib/api.ts': 'overwritten',
      },
    });

  await page.setViewportSize({ width: 1600, height: 950 });
  await page.goto(`/sites/${SITE}`);

  await expect(page.getByText(/Your plugins changed, so the API client was updated/)).toBeVisible({ timeout: 25000 });
  await expect.poll(() => savedPaths(api), { timeout: 15000 }).toEqual(
    expect.arrayContaining(['src/api/index.ts', 'src/api/manifest.json']),
  );
  expect(savedPaths(api)).not.toContain('src/lib/api.ts');
});
