// AUTO-GENERATED by DCMS from this tenant's plugins. Do not edit: it is regenerated when they change.
import {
  createHttpCore,
  type AnalyticsEvent,
  type ChatMessage,
  type CollectionInfo,
  type ContentItem,
  type FormInfo,
  type ListParams,
  type PagedResult,
  type SearchParams,
  type SearchResult,
  type TagIndex,
  type TenantClientOptions,
} from './runtime';
import type { BrandBranding, EnquiriesContactSubmission, NewsPost } from './types';

/** A typed client for this tenant's content API. See API.md beside this file. */
export function createTenantClient(options: TenantClientOptions = {}) {
  const http = createHttpCore(options);
  return {
    media: {
      url: (assetId: string, variant?: string): string => http.mediaUrl(assetId, variant),
    },
    content: http.content,
    submitForm: http.submitForm,
    call: http.call,
    tags: {
      list: (params?: { contentType?: string; field?: string }): Promise<TagIndex> => http.listTags(params),
    },
    "brand": {
      "branding": {
        get: (): Promise<BrandBranding> => http.call<BrandBranding>("GET", `/api/brand/branding`),
      },
    },
    "enquiries": {
      "forms": {
        "contact": {
          submit: (body: EnquiriesContactSubmission): Promise<{ submissionId: string; message: string }> => http.call<{ submissionId: string; message: string }>("POST", `/api/enquiries/forms/contact`, { body }),
        },
      },
    },
    "find": {
      search: (params: SearchParams): Promise<SearchResult> => http.search("find", params),
    },
    "members": {
      auth: http.visitorAuth("members"),
    },
    "news": {
      "post": {
        list: (params?: ListParams): Promise<PagedResult<NewsPost>> => http.listContent<NewsPost>("news", "post", params),
        get: (slug: string): Promise<ContentItem<NewsPost>> => http.getContent<NewsPost>("news", "post", slug),
      },
    },
    "stats": {
      collect: (event: AnalyticsEvent): Promise<void> => http.collect(event, "stats"),
    },
    "support": {
      "chat": {
        history: (conversationId: string): Promise<ChatMessage[]> => http.chatHistory("support", conversationId),
      },
    },
  };
}

export type TenantClient = ReturnType<typeof createTenantClient>;

/** Every content collection this tenant publishes, with hints for which field plays which role. */
export const collections: readonly CollectionInfo[] = [
  { instance: "news", contentType: "post", label: "News", description: "Company announcements and product updates.", titleField: "title", summaryField: "excerpt", imageField: "coverImage", bodyField: "body", bodyFormat: "richtext" },
];

/** Every visitor form this tenant accepts, with its fields. */
export const forms: readonly FormInfo[] = [
  { instance: "enquiries", name: "contact", title: "Contact us", fields: [{ name: "name", label: "Your name", type: "text", required: true, maxLength: 200 }, { name: "email", label: "Email", type: "email", required: true, maxLength: 2000 }, { name: "message", label: "Message", type: "textarea", required: false, maxLength: 4000 }, { name: "newsletter", label: "Send me the newsletter", type: "checkbox", required: false }] },
];

export { ApiError } from './runtime';
export type * from './runtime';
export type * from './types';
