// AUTO-GENERATED by DCMS from this tenant's plugins. Do not edit: it is regenerated when they change.
import type { MediaRef } from './runtime';

export interface BrandBranding {
  /** The brand / site name. */
  name?: string | null;
  /** Short slogan shown alongside the name. */
  tagline?: string | null;
  /** Servable URL of the primary logo image (resolved from the uploaded media asset). */
  logoUrl?: string | null;
  /** Servable URL of the dark-background logo variant, if set. */
  logoDarkUrl?: string | null;
  /** Servable URL of the favicon (resolved from the uploaded media asset). */
  faviconUrl?: string | null;
  /** Primary brand colour as a CSS hex value. */
  primaryColor?: string | null;
  /** Secondary brand colour as a CSS hex value. */
  secondaryColor?: string | null;
  /** Public custom branding values keyed by their configured key. */
  items?: Record<string, string>;
}

export interface EnquiriesContactSubmission {
  /** Your name */
  name: string;
  /** Email */
  email: string;
  /** Message */
  message?: string;
  /** Send me the newsletter */
  newsletter?: boolean;
}

export interface NewsPost {
  /** Post title */
  title: string;
  /** Excerpt shown in lists */
  excerpt?: string;
  /** Post body (rich text) */
  body: string;
  /** Cover image */
  coverImage?: MediaRef;
  /** Tags */
  tags?: string[];
}
