using Dcms.Shared.Kernel.Abstractions;
using Microsoft.EntityFrameworkCore;
using NpgsqlTypes;

namespace Dcms.Shared.Data.Search;

/// <summary>
/// A searchable projection of a published content item. The tsvector is a
/// Postgres generated column (GIN-indexed); a pg_trgm GIN index on the title
/// powers typeahead. One row per content item per tenant.
/// </summary>
public sealed class SearchDocument : TenantEntity
{
    public Guid PluginInstanceId { get; set; }
    public Guid ContentItemId { get; set; }
    public string ContentType { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Body { get; set; } = string.Empty;
    public string Url { get; set; } = string.Empty;
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>Generated by Postgres from Title + Body; never set in code.</summary>
    public NpgsqlTsVector SearchVector { get; set; } = null!;
}

/// <summary>Owns the "search" schema. Written by the content-api indexer, read by search delivery.</summary>
public class SearchDbContext(DbContextOptions<SearchDbContext> options, ITenantContext tenantContext)
    : DbContext(options)
{
    public const string Schema = "search";

    private Guid CurrentTenantId => tenantContext.TenantId ?? Guid.Empty;

    public DbSet<SearchDocument> Documents => Set<SearchDocument>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.HasDefaultSchema(Schema);

        builder.Entity<SearchDocument>(e =>
        {
            e.ToTable("search_documents");
            e.HasKey(d => d.Id);
            e.Property(d => d.ContentType).HasMaxLength(64);
            e.Property(d => d.Title).HasMaxLength(512);
            e.Property(d => d.Url).HasMaxLength(1024);
            e.HasIndex(d => new { d.TenantId, d.ContentItemId }).IsUnique();

            e.HasGeneratedTsVectorColumn(d => d.SearchVector, "simple", d => new { d.Title, d.Body })
                .HasIndex(d => d.SearchVector)
                .HasMethod("GIN");

            e.HasIndex(d => d.Title)
                .HasMethod("GIN")
                .HasOperators("gin_trgm_ops");

            e.HasQueryFilter(d => d.TenantId == CurrentTenantId);
        });
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        StampTenant();
        return base.SaveChangesAsync(cancellationToken);
    }

    public override int SaveChanges()
    {
        StampTenant();
        return base.SaveChanges();
    }

    private void StampTenant()
    {
        var tenantId = CurrentTenantId;
        if (tenantId == Guid.Empty)
        {
            return;
        }
        foreach (var entry in ChangeTracker.Entries<TenantEntity>())
        {
            if (entry.State == EntityState.Added && entry.Entity.TenantId == Guid.Empty)
            {
                entry.Entity.TenantId = tenantId;
            }
        }
    }
}

public sealed class SearchDbContextFactory : Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory<SearchDbContext>
{
    public SearchDbContext CreateDbContext(string[] args)
    {
        var options = new DbContextOptionsBuilder<SearchDbContext>()
            .UseNpgsql(
                "Host=localhost;Port=5432;Database=dcms;Username=dcms;Password=dcms-dev",
                npgsql => npgsql.MigrationsHistoryTable("__ef_migrations_history", SearchDbContext.Schema))
            .Options;
        return new SearchDbContext(options, new NullTenantContext());
    }

    private sealed class NullTenantContext : ITenantContext
    {
        public Guid? TenantId => null;
        public string? TenantSlug => null;
    }
}
