// Regenerates src/icons.ts from lucide-react's icon definitions (ISC). The runtime is copied into
// every site and may not import lucide, so the builder's curated set is embedded as data.
// Run: node packages/site-runtime/scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(join(here, '../../../apps/admin/package.json'));
const lucide = dirname(require.resolve('lucide-react/package.json'));
const version = JSON.parse(readFileSync(join(lucide, 'package.json'), 'utf8')).version;

/** The set authors pick from — chosen for sites, not for app UIs. */
const NAMES = `arrow-right arrow-left arrow-up-right arrow-down chevron-right chevron-down check circle-check x plus minus
star heart thumbs-up smile sparkles award trophy target flag bookmark tag gift ticket percent
calendar clock map-pin map phone mail message-circle send globe house building building-2 store
user users user-round handshake hand-heart briefcase shopping-cart shopping-bag credit-card wallet package truck
music mic headphones camera image video play film book-open graduation-cap lightbulb rocket
shield-check lock zap leaf sprout flower-2 mountain waves sun moon cloud coffee utensils wine
car plane bike dumbbell heart-pulse stethoscope paw-print palette pen-tool code cpu wifi settings wrench
chart-column trending-up info triangle-alert circle-help download upload external-link link search bell layers
quote euro dollar-sign facebook instagram linkedin twitter youtube github`
  .split(/\s+/)
  .filter(Boolean);

const icons = {};
for (const name of NAMES) {
  let source;
  try {
    source = readFileSync(join(lucide, 'dist/esm/icons', `${name}.js`), 'utf8');
  } catch {
    console.warn(`skipped ${name}: not in lucide-react ${version}`);
    continue;
  }
  const body = /createLucideIcon\([^,]+,\s*(\[[\s\S]*\])\s*\);/.exec(source)?.[1];
  if (!body) throw new Error(`cannot read ${name}`);
  // [["path", { d: "...", key: "..." }], ...] → [tag, attrs] without React keys.
  const nodes = Function(`return ${body}`)().map(([tag, attrs]) => {
    const rest = { ...attrs };
    delete rest.key; // React's list key, not an SVG attribute
    return [tag, rest];
  });
  icons[name] = nodes;
}

const out = `// GENERATED by scripts/gen-icons.mjs from lucide-react ${version} (ISC licence,
// https://lucide.dev/license). Do not edit by hand; add a name to the script and re-run it.

/** One SVG element: its tag and attributes, drawn on a 24×24 stroke grid. */
export type IconNode = readonly [tag: string, attrs: Readonly<Record<string, string>>];

export const ICONS: Readonly<Record<string, readonly IconNode[]>> = ${JSON.stringify(icons, null, 1)
  .replace(/\n\s*/g, ' ')
  .replace(/\], "/g, '],\n  "')};

export const ICON_NAMES = Object.keys(ICONS);
`;
writeFileSync(join(here, '../src/icons.ts'), out);
console.log(`wrote ${Object.keys(icons).length} icons`);
