<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="DnsClient" />
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(DcmsSrcRoot)PluginSdk\Dcms.PluginSdk.Abstractions\Dcms.PluginSdk.Abstractions.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Plugins\Dcms.Plugins.All\Dcms.Plugins.All.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Shared\Dcms.Shared.Caching\Dcms.Shared.Caching.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Shared\Dcms.Shared.Data\Dcms.Shared.Data.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Shared\Dcms.Shared.Media\Dcms.Shared.Media.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Shared\Dcms.Shared.Hosting\Dcms.Shared.Hosting.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Shared\Dcms.Shared.Messaging\Dcms.Shared.Messaging.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Shared\Dcms.Shared.Security\Dcms.Shared.Security.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Shared\Dcms.Shared.Storage\Dcms.Shared.Storage.csproj" />
    <ProjectReference Include="$(DcmsSrcRoot)Shared\Dcms.Shared.Vault\Dcms.Shared.Vault.csproj" />
  </ItemGroup>

</Project>
